default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: (\.min\.js$|\.svg$)
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: b969e2851312ca2b24bbec879ba4954341d1bd12 # frozen: v0.15.5
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/hoxbro/clean_notebook
    rev: 2e6f506fab3cdfbe16bc18fd0d24e828db773b74 # frozen: v0.2.1
    hooks:
      - id: clean-notebook
        args: [-i, tags]
  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a # frozen: v2.4.2
    hooks:
      - id: codespell
        exclude: (\.min\.js$|\.svg$|\.html$)
        additional_dependencies:
          - tomli
